name: illuminating-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - numpy
  - pandas
  - scipy
  - matplotlib
  - geopandas
  - rasterio
  - scikit-learn
  - statsmodels
  - pyproj
  - googledrivedownloader
  - spyder
